myLib.derivationError: remove all attributes
It should merge with any set without affecting it's structure, hence we cannot have random attributes. Also moved to standalone since it was doable.